### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by jugmac00** [morepath/morepath_cerebral_todomvc#4]
Although travis is green, both Python 3.6 and Python 3.7 are not run at all as the interpreter are missing.
https://travis-ci.org/github/morepath/morepath_cerebral_todomvc

**Todo**
Use a matrix, see https://github.com/morepath/morepath_static/pull/4 how to fix it.

**Comment by Aniruddha-Shriwant** [comment]
Well @jugmac00 , I would like to work on it :)

**Comment by jugmac00** [comment]
I heard you have experience with it :-)

Thanks, please go for it!

**Comment by rajchordia14** [comment]
can i work on the issue?

**Comment by jugmac00** [comment]
Hi @rajchordia14 - @Aniruddha-Shriwant was a bit faster on this one.

But there are many similar issues to go for. Have a look at any of those
https://github.com/search?q=org%3Amorepath+Update+supported+Python+versions&type=issues

**Comment by Aniruddha-Shriwant** [comment]
Well @jugmac00 , I had done with my 4 PR's for the Hacktoberfest,
Thanks for guiding me from the beginning, will keep exploring new things as I did in this organization's repositories :)

**Comment by jugmac00** [comment]
fixed by #5

**Comment by jugmac00** [comment]
@Aniruddha-Shriwant Good luck for your future! :-)

**Comment by Aniruddha-Shriwant** [comment]
Hey @jugmac00 ,
I think Hacktoberfest has new rules now,
PR won't count if the repo is not participated in Hacktoberfest and in order to participate in Hacktoberfest, the maintainers should add the Hacktoberfest topic to their repo
![image](https://user-images.githubusercontent.com/58624108/94990541-9d793180-059a-11eb-9565-bc2a6f267272.png)

**Comment by jugmac00** [comment]
Hi @Aniruddha-Shriwant 
no worries. The new rules only apply to PRs after Oct 3 - the PRs until then remain valid.
